### ISSUE TITLE
Log which record failed when a batch fails

### ISSUE THREAD

**Issue by aclavio** [marklogic-community/kafka-marklogic-connector#31]
The connector should handle errors that may occur on the writing of records to MarkLogic.

Minimally the error should be logged, and the number (and id's?) of the records which failed to commit should be output.

Ideally, the failed records would be retried a configurable number of times.  The failed records' payloads could optionally be saved to disk or logged.

**Comment by rjrudin** [comment]
What ideas do you have for how a user would configure this via the connector properties file? A DMSDK WriteBatcher handles batch failures via a WriteFailureListener - http://docs.marklogic.com/javadoc/client/com/marklogic/client/datamovement/WriteFailureListener.html . There's not a generic OOTB implementation to use, so we'd be custom coding our own. 

There are existing properties that start with "ml.dmsdk", so that's likely the right prefix to use here.

**Comment by aclavio** [comment]
By default I would want to WriteFailureListener to log how many records failed to insert.

Other desirable configuration items:
```
ml.dmsdk.error.retries - the number of retry attempts for this batch (default: 1)
ml.dmsdk.error.dumpDir - the directory to save any failed payloads (default: ./dump) payloads saved in a text document named with the record's id.
```

The id's and the payloads of the failed documents could also be logged at higher log level (ie: TRACE).

I'm not familiar with how retries could be implemented within the Kafka Connect framework, so my suggestions may need adjustments to reflect the reality of the framework.

**Comment by aclavio** [comment]
Additionally, I think that the detailed logging of errors is probably easier to achieve in the short term, and I'd personally consider a higher priority than the retries.  Perhaps the retry capability should be split into another issue.

**Comment by sjiang99** [comment]
The ability to handle error is a critical feature.
I suggest the behavior on error to be a "best effort" sort. Instead of retry the entire batch again, break the batch into individual messages and commit, the failed individual message will be dumped to the configured location. So we only need to configure the "ml.dmsdk.error.dumpDir" property.

> By default I would want to WriteFailureListener to log how many records failed to insert.
> 
> Other desirable configuration items:
> 
> ```
> ml.dmsdk.error.retries - the number of retry attempts for this batch (default: 1)
> ml.dmsdk.error.dumpDir - the directory to save any failed payloads (default: ./dump) payloads saved in a text document named with the record's id.
> ```
> 
> The id's and the payloads of the failed documents could also be logged at higher log level (ie: TRACE).
> 
> I'm not familiar with how retries could be implemented within the Kafka Connect framework, so my suggestions may need adjustments to reflect the reality of the framework.

**Comment by rjrudin** [comment]
Pinging @fsnow and @ehennum about this - the ability to retry each DocumentWriteOperation in a batch came up with NiFi too. I think it's a generic capability worth adding to DMSDK - or to the Bulk IO API. It's something Kafka and NiFi connectors should be able to configure, not invent. Though I can envision some sort of Listener/callback interface for each item that then fails individually. 

In other words - you can try to invent a solution within a DMSDK QueryFailureListener here, but I recommend trying to add it to DMSDK itself via a PR.

**Comment by ehennum** [comment]
I wonder if this RFE would be best implemented on the enode side.

The REST API implementation of writing a batch could tolerate and report failures -- basically, wrapping a try-catch around each document write if authorized by either a parameter or REST server property.
