### ISSUE TITLE
example of distributed mode properties file 

### ISSUE THREAD

**Issue by iowusu** [marklogic-community/kafka-marklogic-connector#9]
There is currently no example of distributed mode properties file for the connector.

**Comment by rjrudin** [comment]
Does this refer to "marklogic-connect-standalone.properties" or "marklogic-sink.properties"?

If it's the former, I feel it's outside the scope of this connector. There's nothing in "marklogic-connect-standalone.properties" (nor in the SSL one) that has anything to do with this connector. All of the config in both files is connector-agnostic and is general to Kafka Connect itself. 

Therefore, I recommend not doing this because it would force this project to have to maintain a file that is has nothing to do with. If someone is seeking an example of a distributed mode properties file, they should be able to find that in the Kafka Connect documentation.

**Comment by BillFarber** [comment]
Using this connector either with a Kafka cluster requires no changes.
Using multiple instances of this connector requires very little configuration.
Using this connector with a ML cluster and load balancer also requires a small change.

I have created a short set of notes that I think are worth including in the project to assist users. I will add that document soon.

**Comment by BillFarber** [comment]
I added a short set of notes for setting up the connector in a distributed system. (https://github.com/marklogic-community/kafka-marklogic-connector/blob/master/examples/ScalingConsiderations.md)
